### ISSUE TITLE
Wrong volume management?

### ISSUE THREAD

**Issue by lboclboc** [GerritCodeReview/k8s-gerrit#12]
It seems the gerrit-site volume is created with a volume template - meaning it will be persistent. But that is only mounted as
/var/gerrit.

The real git repository volume git-repositories is mounted under /var/mnt/git but is created as a PVC by the chart, not as a volume template. Which means it will be lost if the deployment is restarted.

**Comment by thomasdraebing** [comment]
To make the git-repositories survive deployment restarts and more importantly deletion of the chart installation or change of the chart installation name, the PVC should be installed separately and referenced under `gitRepositoryStorage.externalPVC` in the `values.yaml`.
However, you are right, it would be better to use a volume template as a default. Would you be wiling to contribute that fix?
Please note, that the repository on GitHub is just a mirror. Pull requests are not accepted here. Changes will be reviewed in this [project](https://gerrit-review.googlesource.com/admin/repos/k8s-gerrit,general) in gerrit-review.

**Comment by thomasdraebing** [comment]
I was wrong with my previous comment. Sorry for that. We can't use a volume template here, because the volume will be shared by all pods of the StatefulSet. AFAIK that does not work with PersistentVolumeClaimTemplates. So as mentioned before, use the feature of the chart to use a manually created PVC that won't be deleted together with the chart.

**Comment by lboclboc** [comment]
Ah, of course. Sorry for that and thanks.
