### ISSUE TITLE
how to change admin password?

### ISSUE THREAD

**Issue by hillbun** [GerritCodeReview/k8s-gerrit#16]
I install helm-charts of gerrit, but login in admin as now password.

How to change admin password?

**Comment by thomasdraebing** [comment]
In Gerrit the first user logging in via the UI will become admin. All subsequent users will have to be granted admin rights.
Issues on GitHub are not regularly checked, since this is just a mirror of the repository on [gerrit-review](https://gerrit-review.googlesource.com/q/project:k8s-gerrit). Please use the Gerrit mailing list (https://groups.google.com/g/repo-discuss?hl=en) for questions.
