### ISSUE TITLE
Allow Gerrit helm chart to enable SSHd

### ISSUE THREAD

**Issue by Venthe** [GerritCodeReview/k8s-gerrit#4]
Currently there is no option to enable SSHd, nor it is not exposed on container or service.

I've actually have changed the code, so after I verify it that it works I might request pull; if that's okay.

**Comment by thomasdraebing** [comment]
Hi @Venthe,

contributing this would be more than welcome. Note, that changes won't be accepted via pull request on GitHub, since this GitHub repository is only a mirror. The project is maintained in in Gerrit [here](https://gerrit-review.googlesource.com/admin/repos/k8s-gerrit).

Looking forward to seeing your contribution,
Thomas

**Comment by Venthe** [comment]
Which is not ideal :) While I agree that main gerrit should be on... Gerrit, but public projects should not be gatekeeped.

But of course it's not the topic here. I've pushed my branch and I've already broke the relation chain, each one should be standalone. So please review, at your own leisure. :)

**Comment by Venthe** [comment]
Merged with 7994997e88ad5044096f2b68f2afffe9bf658656
